// <auto-generated />
using System;
using CareConnections.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareConnections.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CareConnections.Shared.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            BirthDate = new DateTime(1980, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            Gender = 0,
                            LastName = "Driver"
                        },
                        new
                        {
                            ClientId = 2,
                            BirthDate = new DateTime(1985, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Scarlet",
                            Gender = 1,
                            LastName = "Jonahson"
                        },
                        new
                        {
                            ClientId = 3,
                            BirthDate = new DateTime(1982, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jessica",
                            Gender = 1,
                            LastName = "Albo"
                        },
                        new
                        {
                            ClientId = 4,
                            BirthDate = new DateTime(1972, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jwayne",
                            Gender = 0,
                            LastName = "Dohnson"
                        },
                        new
                        {
                            ClientId = 5,
                            BirthDate = new DateTime(1940, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Prad",
                            Gender = 0,
                            LastName = "Bitt"
                        });
                });

            modelBuilder.Entity("CareConnections.Shared.Domain.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("AuthorizedClients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AuthorizedClients = "1,2,4",
                            Name = "Sander"
                        },
                        new
                        {
                            EmployeeId = 2,
                            AuthorizedClients = "2,3",
                            Name = "Peter"
                        },
                        new
                        {
                            EmployeeId = 3,
                            AuthorizedClients = "3,4,5",
                            Name = "Chris"
                        });
                });

            modelBuilder.Entity("CareConnections.Shared.Domain.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"), 1L, 1);

                    b.Property<string>("CarePlanGoalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPriority")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            CarePlanGoalId = "",
                            ClientId = "1",
                            CreatedAt = new DateTime(2019, 8, 12, 15, 22, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Sander",
                            HasPriority = false,
                            Subject = "High bloodpressure",
                            Text = "Client seems to have excessive lifestyle, causing high bloodpressure. Adviced to stop driving so fast."
                        },
                        new
                        {
                            ReportId = 2,
                            CarePlanGoalId = "2",
                            ClientId = "1",
                            CreatedAt = new DateTime(2019, 8, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Sander",
                            HasPriority = false,
                            Subject = "Short attention span",
                            Text = "Client only pays attention for 9.8 seconds"
                        },
                        new
                        {
                            ReportId = 3,
                            CarePlanGoalId = "",
                            ClientId = "1",
                            CreatedAt = new DateTime(2019, 8, 10, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Sander",
                            HasPriority = true,
                            Subject = "Burn marks",
                            Text = "Mr. Driver burnt his hand cooking dinner."
                        },
                        new
                        {
                            ReportId = 4,
                            CarePlanGoalId = "",
                            ClientId = "2",
                            CreatedAt = new DateTime(2019, 8, 12, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Peter",
                            HasPriority = false,
                            Subject = "Trouble walking",
                            Text = "Ms. Jonahson has trouble walking for more than a few minutes at a time"
                        },
                        new
                        {
                            ReportId = 5,
                            CarePlanGoalId = "",
                            ClientId = "2",
                            CreatedAt = new DateTime(2019, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Sander",
                            HasPriority = false,
                            Subject = "Random language loss",
                            Text = "Client sometimes seems lost trying to translate her words, and she can only speak Japanese for a few minutes"
                        },
                        new
                        {
                            ReportId = 6,
                            CarePlanGoalId = "",
                            ClientId = "2",
                            CreatedAt = new DateTime(2019, 8, 8, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Peter",
                            HasPriority = false,
                            Subject = "Quiet day",
                            Text = "Everything went well today"
                        },
                        new
                        {
                            ReportId = 7,
                            CarePlanGoalId = "",
                            ClientId = "3",
                            CreatedAt = new DateTime(2019, 8, 12, 16, 50, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Peter",
                            HasPriority = false,
                            Subject = "Quiet day",
                            Text = "Nothing special happened"
                        },
                        new
                        {
                            ReportId = 8,
                            CarePlanGoalId = "1",
                            ClientId = "3",
                            CreatedAt = new DateTime(2019, 8, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Peter",
                            HasPriority = false,
                            Subject = "Physical exercise",
                            Text = "Client tried surfing today to regain mobility, went well"
                        },
                        new
                        {
                            ReportId = 9,
                            CarePlanGoalId = "1",
                            ClientId = "3",
                            CreatedAt = new DateTime(2019, 8, 4, 11, 19, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Chris",
                            HasPriority = false,
                            Subject = "Sprained ankle",
                            Text = "Ms. Albo sprained her ankle"
                        },
                        new
                        {
                            ReportId = 10,
                            CarePlanGoalId = "1",
                            ClientId = "4",
                            CreatedAt = new DateTime(2019, 8, 12, 15, 22, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Sander",
                            HasPriority = false,
                            Subject = "Too much protein",
                            Text = "Mr. Dohnson exceeded his agreed limit of maximum 5 protein shakes a day"
                        },
                        new
                        {
                            ReportId = 11,
                            CarePlanGoalId = "",
                            ClientId = "4",
                            CreatedAt = new DateTime(2019, 8, 10, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Remco",
                            HasPriority = false,
                            Subject = "Couldn't get out of bed",
                            Text = "Client refused to get up and stayed in bed all day"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
