//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareKickoff.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CareKickoff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;1&quot;,
        ///    &quot;DisplayName&quot;: &quot;Careplan Paul Driver, 2019&quot;,
        ///    &quot;ClientId&quot;: &quot;1&quot;,
        ///    &quot;Goals&quot;: [
        ///      {
        ///        &quot;DisplayName&quot;: &quot;Drive slower&quot;,
        ///        &quot;GoalId&quot;: &quot;1&quot;
        ///      },
        ///      {
        ///        &quot;DisplayName&quot;: &quot;Work on focus&quot;,
        ///        &quot;GoalId&quot;: &quot;2&quot;
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;1&quot;,
        ///    &quot;DisplayName&quot;: &quot;Careplan&quot;,
        ///    &quot;ClientId&quot;: &quot;2&quot;,
        ///    &quot;Goals&quot;: [
        ///      {
        ///        &quot;DisplayName&quot;: &quot;Get back sense of direction&quot;,
        ///        &quot;GoalId&quot;: &quot;1&quot;
        ///      },
        ///      {
        ///        &quot;DisplayName&quot;: &quot;Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string careplans {
            get {
                return ResourceManager.GetString("careplans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;FirstName&quot;: &quot;Paul&quot;,
        ///    &quot;LastName&quot;: &quot;Driver&quot;,
        ///    &quot;BirthDate&quot;: &quot;1980-05-20T00:00:00&quot;,
        ///    &quot;Gender&quot;: &quot;male&quot;,
        ///    &quot;NativeId&quot;: &quot;1&quot;
        ///  },
        ///  {
        ///    &quot;FirstName&quot;: &quot;Scarlet&quot;,
        ///    &quot;LastName&quot;: &quot;Jonahson&quot;,
        ///    &quot;BirthDate&quot;: &quot;1985-01-11T00:00:00&quot;,
        ///    &quot;Gender&quot;: &quot;female&quot;,
        ///    &quot;NativeId&quot;: &quot;2&quot;
        ///  },
        ///  {
        ///    &quot;FirstName&quot;: &quot;Jessica&quot;,
        ///    &quot;LastName&quot;: &quot;Albo&quot;,
        ///    &quot;BirthDate&quot;: &quot;1982-04-11T00:00:00&quot;,
        ///    &quot;Gender&quot;: &quot;female&quot;,
        ///    &quot;NativeId&quot;: &quot;3&quot;
        ///  },
        ///  {
        ///    &quot;FirstName&quot;: &quot;Jwayne&quot;,
        ///    &quot;LastName&quot;: &quot;Do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Sander&quot;,
        ///    &quot;EmployeeId&quot;: &quot;1&quot;,
        ///    &quot;AuthorizedClients&quot;: [ &quot;1&quot;, &quot;2&quot;, &quot;4&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Peter&quot;,
        ///    &quot;EmployeeId&quot;: &quot;2&quot;,
        ///    &quot;AuthorizedClients&quot;: [ &quot;2&quot;, &quot;3&quot; ]
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Chris&quot;,
        ///    &quot;EmployeeId&quot;: &quot;3&quot;,
        ///    &quot;AuthorizedClients&quot;: [ &quot;3&quot;, &quot;4&quot;, &quot;5&quot; ]
        ///  }
        ///].
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Subject&quot;: &quot;High bloodpressure&quot;,
        ///    &quot;Text&quot;: &quot;Client seems to have excessive lifestyle, causing high bloodpressure. Adviced to stop driving so fast.&quot;,
        ///    &quot;HasPriority&quot;: false,
        ///    &quot;CarePlanGoalId&quot;: &quot;&quot;,
        ///    &quot;ClientId&quot;: &quot;1&quot;,
        ///    &quot;CreatedBy&quot;: &quot;Sander&quot;,
        ///    &quot;CreatedAt&quot;: &quot;2019-08-12T15:22:00&quot;
        ///  },
        ///  {
        ///    &quot;Subject&quot;: &quot;Short attention span&quot;,
        ///    &quot;Text&quot;: &quot;Client only pays attention for 9.8 seconds&quot;,
        ///    &quot;HasPriority&quot;: false,
        ///    &quot;CarePlanGoalId&quot;: &quot;2&quot;,
        ///    &quot;ClientId&quot;: &quot;1&quot;,
        ///    &quot;CreatedBy&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
    }
}
